// src/lib/tables.ts
export const T = {
  businessInfo: 'business_info',
  shopStaff: 'shop_staff',
  customers: 'customers',
  products: 'products',
  sales: 'sales',
  saleItems: 'sale_items',
  reminders: 'reminders',
  vault: 'vault',
  vaultEntries: 'vault_entries',
  sideBusinesses: 'side_businesses',
  sideBusinessItems: 'side_business_items',
  sideBusinessSales: 'side_business_sales',
  inventoryMovements: 'inventory_movements',
  refunds: 'refunds',
  users: 'users',
  customerShoppingLists: 'customer_shopping_lists',
  vouchers: 'vouchers',
  customerVouchers: 'customer_vouchers',
} as const;
